api:
  dashboard: true
  insecure: true  # Ativa o dashboard de forma insegura, apenas em ambientes de desenvolvimento

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  portainerview:
    address: ":9001"  # EntryPoint para acessar Portainer na porta 9001

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true  # Habilita a observação para mudanças dinâmicas nos containers

certificatesResolvers:
  dev_server_tlschallenge:
    acme:
      email: your-email@example.com
      storage: /letsencrypt/acme.json
      tlsChallenge: {}

# Não sãoo necessários routers e services aqui, pois são criados pelas labels
