export enum TipoDocumentoEnum {
  PROPOSTA_INDIVIDUAL = 'Proposta Individual',
  DOCUMENTO_AVULSO = 'Documento Avulso',
  CPF = 'CPF',
  RG = 'RG',
  DPS='DPS - Declaração pessoal de saúde',
  COMPROVANTE_RENDA = 'Comprovante de Renda',
  COMPROVANTE_RESIDENCIA = 'Comprovante de Residencia',
  DECLARACAO_MEDICA = 'Declaração Médica',
  DPS_COMPLEMENTAR = 'DPS - Declaração pessoal de saúde complementar',
  PRONTUARIOS_MÉDICOS = 'Prontuários Médicos',
  AVISO_ALTA_MEDICA = 'Aviso de Alta Médica',
  LAUDO_EXAMES_MEDICOS = 'Laudo de Exames Médicos',
  PARECER_MEDICO = 'Parecer Médico',
  CERTIDOES = 'Certidões',
  HABILITACAO = 'Habilitação',
  PROCESSO_BENEFICIO = 'Processo de Benefício',
  CERTIFICADOS = 'Certificados',
  CARTA_COBRANÇA = 'Carta de Cobrança',
  CARTA_CANCELAMENTO = 'Carta de Cancelamento',
  INFORME_RENDIMENTOS = 'Informe de Rendimentos',
  EXTRATO_PLANOS = 'Extrato dos Planos',
  COMUNICADO_RECUSA = 'Comunicado de Recusa',
  CONTRATO_SOCIAL = 'Contrato Social',
  GFIP = 'GFIP',
  COMPROVANTE_ASSINATURA_ELETRONICA = 'Comprovante de Assinatura Eletrônica',
  TERMO_PORTABILIDADE = 'Termo de portabilidade',
  CADASTRO_ESPECIFICO_INSS = '(CEI) Cadastro Específico do INSS',
  RESUMO_CAPITAL_SEGURADO_FUNPRESP = 'Resumo Capital Segurado Funpresp',
  NAO_CLASSIFICADO = 'Não Classificado',
}

export var ListaTiposDocumento: Array<TipoDocumentoEnum> = [
  TipoDocumentoEnum.PROPOSTA_INDIVIDUAL,
  TipoDocumentoEnum.AVISO_ALTA_MEDICA,
  TipoDocumentoEnum.CADASTRO_ESPECIFICO_INSS,
  TipoDocumentoEnum.CARTA_CANCELAMENTO,
  TipoDocumentoEnum.CARTA_COBRANÇA,
  TipoDocumentoEnum.CERTIDOES,
  TipoDocumentoEnum.CERTIFICADOS,
  TipoDocumentoEnum.COMPROVANTE_ASSINATURA_ELETRONICA,
  TipoDocumentoEnum.COMPROVANTE_RENDA,
  TipoDocumentoEnum.COMPROVANTE_RESIDENCIA,
  TipoDocumentoEnum.COMUNICADO_RECUSA,
  TipoDocumentoEnum.CONTRATO_SOCIAL,
  TipoDocumentoEnum.CPF,
  TipoDocumentoEnum.DECLARACAO_MEDICA,
  TipoDocumentoEnum.DOCUMENTO_AVULSO,
  TipoDocumentoEnum.DPS,
  TipoDocumentoEnum.DPS_COMPLEMENTAR,
  TipoDocumentoEnum.EXTRATO_PLANOS,
  TipoDocumentoEnum.GFIP,
  TipoDocumentoEnum.HABILITACAO,
  TipoDocumentoEnum.INFORME_RENDIMENTOS,
  TipoDocumentoEnum.LAUDO_EXAMES_MEDICOS,
  TipoDocumentoEnum.NAO_CLASSIFICADO,
  TipoDocumentoEnum.PARECER_MEDICO,
  TipoDocumentoEnum.PROCESSO_BENEFICIO,
  TipoDocumentoEnum.PRONTUARIOS_MÉDICOS,
  TipoDocumentoEnum.PROPOSTA_INDIVIDUAL,
  TipoDocumentoEnum.RESUMO_CAPITAL_SEGURADO_FUNPRESP,
  TipoDocumentoEnum.RG,
  TipoDocumentoEnum.TERMO_PORTABILIDADE,
]

