global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'micro-devops-app'
    static_configs:
      - targets: ['app:4200']

  - job_name: 'jaeger'
    metrics_path: /metrics
    static_configs:
      - targets: ['jaeger:16686']

  - job_name: 'electron-app'
    static_configs:
      - targets: ['dev-server.mshome.net:3000'] # Supondo que as métricas estejam expostas na porta 3000
