
  export const environment = {
    PRODUCTION:false,
    AMBIENTE: 'homol',
    SERVICE:'http://sgr-angular-backoffice-nodejs-homol.homologacao.com.br',
    REST_URL: 'https://apicinterno-homol.sicoob.com.br/sicoob/interno',
    API_GATEWAY: 'http://apimanager-homol.homologacao.com.br:8280',
    AUTH_GATEWAY: 'http://apimanager-homol.homologacao.com.br:8280/token',
    REVOKE_GATEWAY: 'http://apimanager-homol.homologacao.com.br:8280/revoke',
    SSO_GATEWAY:'https://cas-homol.sisbr.coop.br/cas',
    APPLICATION_TOKEN:'Basic dWR4MFliS3pSaWJFbzN3STFFNG9ZZm1nUl9vYTpxVkEwOXY3YkxJR3A2d2ZGcXpsRW4zWkhWRFFh',
    COOPERATIVA: '/cooperativa',
    CORRETORAS: '/corretoras',
    CENTRAL: '/central',
    DEVOLUCAO: '/devolucao',
    DOMAIN_SVE: '/sve',
    DOMAIN_SVD: '/svd',
    STATUS: '/status',
    SERVICE_SVE: 'http://sve-angular-backoffice-nodejs-hom.homologacao.com.br',
    SERVICE_VGBL: 'http://vgbl-angular-backoffice-nodejs-vgbl.apphom.homologacao.com.br/previdencia-vgbl',
    SERVICE_SPR: 'http://spr-angular-backoffice.apphom.homologacao.com.br/spr',
    SEGURO_PRESTAMISTA: '/seguro-prestamista/v1',
    SERVICE_SGR_PATRIMONIAL: 'http://sgr-patrimonial-angular-backoffice.apphom.homologacao.com.br/sgr-patrimonial/',
    SERVICE_SRE: 'http://sre-angular-backoffice-nodejs.apphom.homologacao.com.br/seguro-residencial',
    SERVICE_SVD: 'http://svd-angular-backoffice-nodejs.apphom.homologacao.com.br',
    SERVICE_SGT: 'http://sgt-angular-backoffice-nodejs.apphom.homologacao.com.br/sgt',
    SERVICE_SGCEL: 'http://sgcel-angular-backoffice-nodejs.apphom.homologacao.com.br/sgcel',
    SERVICE_VIDA_COTADO: 'http://cas-homol.homologacao.com.br:8080/cas/idp/profile/SAML2/Unsolicited/SSO?providerId=cotadorvg-sicoob',
    CLIENT_ID: 'udx0YbKzRibEo3wI1E4oYfmgR_oa',
    SERVICE_SRB: '[COLCOAR URL AQUI]',
  };
