
  export const environment = {
    PRODUCTION:true,
    AMBIENTE: 'prod',
    SERVICE: 'https://portal.sisbr.coop.br/sgr/',
    REST_URL: 'https://portal.sisbr.coop.br/sicoob/interno',
    API_GATEWAY: 'https://portal.sisbr.coop.br/sicoob/interno',
    AUTH_GATEWAY: 'https://portal.sisbr.coop.br/auth/token',
    REVOKE_GATEWAY: 'https://portal.sisbr.coop.br/auth/revoke',
    SSO_GATEWAY: 'https://portal.sisbr.coop.br/cas',
    APPLICATION_TOKEN: 'Basic ME13ZjFmdjJISF9qM1JoWkpsZ2VGcFg2NFFZYTpub1YzN3BRZUdMSVdKaEk0RDBmcXNvZVFOd2dh',
    COOPERATIVA: '/cooperativa',
    CORRETORAS: '/corretoras',
    CENTRAL: '/central',
    DEVOLUCAO: '/devolucao',
    DOMAIN_SVE: '/sve',
    DOMAIN_SVD: '/svd',
    STATUS: '/status',
    SERVICE_SVE: 'https://portal.sisbr.coop.br',
  	SEGURO_PRESTAMISTA: '/seguro-prestamista/v1',
    SERVICE_SRE: 'https://portal.sisbr.coop.br/seguro-residencial',
    SERVICE_SGR_PATRIMONIAL: 'https://portal.sisbr.coop.br/sgr-patrimonial',
    SERVICE_VGBL: 'https://portal.sisbr.coop.br/previdencia-vgbl',
    SERVICE_SPR: 'https://portal.sisbr.coop.br/spr',
    SERVICE_SVD: 'https://portal.sisbr.coop.br',
    SERVICE_SGT: 'https://portal.sisbr.coop.br/sgt',
    SERVICE_SGCEL: 'https://portal.sisbr.coop.br/sgcel',
    SERVICE_VIDA_COTADO: 'https://sca.sicoob.com.br/cas/idp/profile/SAML2/Unsolicited/SSO?providerId=cotadorvg-sicoob',
    CLIENT_ID: '0Mwf1fv2HH_j3RhZJlgeFpX64QYa',
    SERVICE_SRB: '[COLCOAR URL AQUI]',
  };
