export const environment = {
  PRODUCTION: false,
  API_GATEWAY: 'http://apit.homologacao.com.br:8280',
  AUTH_GATEWAY: 'http://apit.homologacao.com.br:8280/token',
  REVOKE_GATEWAY: 'http://apit.homologacao.com.br:8280/revoke',
  SSO_GATEWAY: 'https://boti.sisbr.coop.br/cas',
  APPLICATION_TOKEN: 'Basic cTRXMEVYQnBiN3pDOHlEY2V6M3R2NnRPRWtjYTpIR3FwMjh4TVZrQXZjVURvWm5uMnRLbU95UGth',
  SERVICE: 'http://sgr-angular-backoffice-nodejs-ti',
  // SERVICE: 'http://localhost:4200',
  //REST_URL: 'http://apit.homologacao.com.br:8280',
  REST_URL: 'https://apic-ti.sicoob.com.br/sicoob/interno',
  // REST_URL: 'http://localhost:9080',
  PORT: '3000',
  COOPERATIVA: '/cooperativa',
  CORRETORAS: '/corretoras',
  CENTRAL: '/central',
  DEVOLUCAO: '/devolucao',
  STATUS: '/status',
  SERVICE_SVE: 'http://localhost:4200',
  DOMAIN_SVE: '/sve',
  DOMAIN_SVD: '/svd',
  SERVICE_SRE: 'http://localhost:4201/seguro-residencial',
  SERVICE_SGR_PATRIMONIAL: 'http://localhost:4201/sgr-patrimonial',
  SERVICE_VGBL: 'http://localhost:4200/previdencia-vgbl',
  SERVICE_SPR: 'http://localhost:4200/spr',
  SERVICE_SVD: 'http://localhost:4200',
  SERVICE_SGT: 'http://localhost:4201/sgt',
  SERVICE_SGCEL: 'http://localhost:4201/sgcel',
  SERVICE_SRB: 'http://srb-angular-backoffice-nodejs.appdev.homologacao.com.br/regulacao-beneficio/',
  //não tem para local e ti
  SERVICE_VIDA_COTADO: 'http://cas-homol.homologacao.com.br:8080/cas/idp/profile/SAML2/Unsolicited/SSO?providerId=cotadorvg-sicoob',

  AMBIENTE: 'env',
  SEGURO_PRESTAMISTA: '/seguro-prestamista/v1',
  ClIENT_ID:'q4W0EXBpb7zC8yDcez3tv6tOEkca'
};
