
  export const environment = {
    PRODUCTION: false,
    AMBIENTE: 'env',
    SGR_API_PATH: '/sgr/v1',
    //REST_URL: 'http://apit.homologacao.com.br:8280',
    REST_URL: 'https://apic-ti.sicoob.com.br/sicoob/interno',
    PORT: '3000',
    API_GATEWAY: 'http://apit.homologacao.com.br:8280',
    AUTH_GATEWAY: 'http://apit.homologacao.com.br:8280/token',
    REVOKE_GATEWAY: 'http://apit.homologacao.com.br:8280/revoke',
    SSO_GATEWAY: 'https://boti.sisbr.coop.br/cas',
    APPLICATION_TOKEN: 'Basic cTRXMEVYQnBiN3pDOHlEY2V6M3R2NnRPRWtjYTpIR3FwMjh4TVZrQXZjVURvWm5uMnRLbU95UGth',
    SERVICE: 'http://sgr-angular-backoffice-nodejs-ti',
    SERVICE_SVE: 'http://sve-angular-backoffice-nodejs-ti.homologacao.com.br',
    SERVICE_VGBL: 'http://vgbl-angular-backoffice-nodejs-vgbl.appdev.homologacao.com.br/previdencia-vgbl',
    SERVICE_SPR: 'http://spr-angular-backoffice.appdev.homologacao.com.br/spr',
    SERVICE_SRE: 'http://sre-angular-backoffice-nodejs.appdev.homologacao.com.br/seguro-residencial',
    SERVICE_SGR_PATRIMONIAL: 'http://sgr-patrimonial-angular-backoffice.appdev.homologacao.com.br/sgr-patrimonial/',
    SERVICE_SVD: 'http://svd-angular-backoffice.appdev.homologacao.com.br',
    SERVICE_SGT: 'http://sgt-angular-backoffice-nodejs.appdev.homologacao.com.br/sgt',
    SERVICE_SGCEL: 'http://sgcel-angular-backoffice-nodejs.appdev.homologacao.com.br/sgcel',
    SERVICE_SRB: 'http://srb-angular-backoffice-nodejs.appdev.homologacao.com.br/regulacao-beneficio/',
    //Não tem para ti
    SERVICE_VIDA_COTADO: 'http://cas-homol.homologacao.com.br:8080/cas/idp/profile/SAML2/Unsolicited/SSO?providerId=cotadorvg-sicoob',
    COOPERATIVA: '/cooperativa',
    CORRETORAS: '/corretoras',
    CENTRAL: '/central',
    DEVOLUCAO: '/devolucao',
    DOMAIN_SVE: '/sve',
    DOMAIN_SVD: '/svd',
    STATUS: '/status',
    SEGURO_PRESTAMISTA: '/seguro-prestamista/v1',
    ClIENT_ID:'q4W0EXBpb7zC8yDcez3tv6tOEkca'
  };
