export enum ProdutoPropostaEnum {
  VIDA_INDIVIDUAL = 'VIDA_INDIVIDUAL',
  VIDA_MULHER = 'VIDA_MULHER',
  VIDA_SIMPLES = 'VIDA_SIMPLES',
  RISCO_PREVI = 'RISCO_PREVI',
  VIDA_EMPRESARIAL = 'VIDA_EMPRESARIAL'
}
