export enum SituacaoPropostaEnum {
  EM_ANALISE = 'EM_ANALISE',
  PENDENTE = 'PENDENTE',
  RECUSADA = 'RECUSADA',
  CANCELADA = 'CANCELADA',
  IMPLANTADA = 'IMPLANTADA',
  AGUARDANDO_PROCESSAMENTO = 'AGUARDANDO_PROCESSAMENTO'
}
