export enum StatusFaturamentoEnum {
  ENVIADO = 'ARQUIVO_ENVIADO',
  PROCESSAMENTO = 'EM_PROCESSAMENTO',
  DISPONIVEL = 'FATURA_DISPONIVEL',
  CONTESTADA = 'FATURA_CONTESTADA',
  CANCELADO = 'FATURAMENTO_CANCELADO',
  CONCLUIDO = 'FATURAMENTO_CONCLUIDO'
}
