export enum TiposAquivosFaturamentosEnum {
  ARQUIVO_TXT = 'ARQUIVO_TXT',
  ARQUIVO_EXTRA_SISTEMA = 'ARQUIVO_EXTRA_SISTEMA',
  OUTRAS_DOCUMENTACOES = 'OUTRAS_DOCUMENTACOES',
  ARQUIVO_FATURA = 'ARQUIVO_FATURA'
}
